site_name: Adam J. Vogt
site_url: https://ajvogt.github.io
theme:
  name: material
  features:
    # - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - mkdocs-jupyter
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/adamjvogt
    - icon: fontawesome/brands/github
      link: https://github.com/ajvogt
nav:
    - Home: index.md
    - Projects:
        - Introduction: projects.md
        - MNIST Image Classifier: ImageClassification.ipynb
        - Voting Record Classifier: VotingRecord.ipynb
        - COVID-19 Pandemic Analysis: missouri_analysis.md
        - NFL Pickem Optimization: nfl_pickem.md
