site_name: Adam J. Vogt
site_url: https://ajvogt.github.io
theme:
  name: material
  features:
    - toc.follow
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - admonition
  - toc:
      permalink: True
      toc_depth: 2-4
plugins:
  - mkdocs-jupyter
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/adamjvogt
    - icon: fontawesome/brands/github
      link: https://github.com/ajvogt
nav:
    - Home: index.md
    - MNIST Image Classifier: ImageClassification.ipynb
    - Voting Record Classifier: VotingRecord.ipynb
    - COVID-19 Pandemic Analysis: missouri_analysis.md
    - NFL Pickem Optimization: nfl_pickem.md


